name: AtomiCloud CI Environment
description: "Setups AtomiCloud's CI environment Environment"
inputs:
  install_url:
    description: "Installation URL that will contain a script to install Nix."
  install_options:
    description: "Additional installer flags passed to the installer script."
  nix_path:
    description: "Set NIX_PATH environment variable."
  extra_nix_config:
    description: "gets appended to `/etc/nix/nix.conf` if passed."
  binary_cache:
    description: "The list of binary caches to use separated by spaces"
runs:
  using: "composite"
  steps:
    - name: Install Nix
      run: ${{ github.action_path }}/scripts/install-nix.sh
      shell: bash
      env:
        INPUT_INSTALL_URL: "${{ inputs.install_url }}"
        INPUT_INSTALL_OPTIONS: "${{ inputs.install_options }}"
        INPUT_NIX_PATH: "${{ inputs.nix_path }}"
        INPUT_EXTRA_NIX_CONFIG: "${{ inputs.extra_nix_config }}"

    - name: Install Dependent binaries with Nix
      run: ${{ github.action_path }}/scripts/atomi.sh
      shell: bash
    - name: Add user as trusted user
      run: ${{ github.action_path }}/scripts/include_trusted_user.sh
      shell: bash
    - name: Use Binary Caches
      run: ${{ github.action_path }}/scripts/binary_cache.sh
      shell: bash
      env:
        BINARY_CACHE: "${{ inputs.binary_cache }}"
