name: "Continous Integration"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Install Nix
        run: scripts/install-nix.sh
        env:
          INPUT_INSTALL_URL: ""
          INPUT_INSTALL_OPTIONS: ""
          INPUT_NIX_PATH: ""
          INPUT_EXTRA_NIX_CONFIG: ""

      - name: Install atomi
        run: scripts/atomi.sh

      - name: Use Cachix
        run: cachix use kirinnee-sample-binary-cache

      - name: Run Pre-commit checks
        run: nix-shell nix/shells.nix -A lint-ci --run scripts/ci/pre-commit.sh
