name: "Continous Integration"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: ubuntu-20.04
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix
        run: |
          nix-env -i cachix
          cachix use kirinnee-sample-binary-cache

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Run Pre-commit checks
        run: nix-shell nix/shells.nix -A lint-ci --run scripts/ci/pre-commit.sh
